name: Build/run docker image
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and run container
        run: |
          docker build -t testimage .
          docker run -it --rm -d -p 8080:80 --name web testimage
      - name: Test container
        run: |
          curl "http://localhost:8080/statusfile"
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
  
      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev
          docker build -t us-east1-docker.pkg.dev/$GOOGLE_PROJECT/myapp/nginx:latest .
          docker push us-east1-docker.pkg.dev/$GOOGLE_PROJECT/myapp/nginx:latest
