name: Build/run docker image
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and run container
        run: |
          docker build -t testimage .
          docker run -it --rm -d -p 8080:80 --name web testimage
          sleep 5
          docker container ls
          curl "http://localhost:8080/"
